//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HPCakes.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cakeshopEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cakeshopEntities object using the connection string found in the 'cakeshopEntities' section of the application configuration file.
        /// </summary>
        public cakeshopEntities() : base("name=cakeshopEntities", "cakeshopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cakeshopEntities object.
        /// </summary>
        public cakeshopEntities(string connectionString) : base(connectionString, "cakeshopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cakeshopEntities object.
        /// </summary>
        public cakeshopEntities(EntityConnection connection) : base(connection, "cakeshopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<category> categories
        {
            get
            {
                if ((_categories == null))
                {
                    _categories = base.CreateObjectSet<category>("categories");
                }
                return _categories;
            }
        }
        private ObjectSet<category> _categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<product> products
        {
            get
            {
                if ((_products == null))
                {
                    _products = base.CreateObjectSet<product>("products");
                }
                return _products;
            }
        }
        private ObjectSet<product> _products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<contact_us> contact_us
        {
            get
            {
                if ((_contact_us == null))
                {
                    _contact_us = base.CreateObjectSet<contact_us>("contact_us");
                }
                return _contact_us;
            }
        }
        private ObjectSet<contact_us> _contact_us;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<menu> menus
        {
            get
            {
                if ((_menus == null))
                {
                    _menus = base.CreateObjectSet<menu>("menus");
                }
                return _menus;
            }
        }
        private ObjectSet<menu> _menus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<news> news
        {
            get
            {
                if ((_news == null))
                {
                    _news = base.CreateObjectSet<news>("news");
                }
                return _news;
            }
        }
        private ObjectSet<news> _news;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<order> orders
        {
            get
            {
                if ((_orders == null))
                {
                    _orders = base.CreateObjectSet<order>("orders");
                }
                return _orders;
            }
        }
        private ObjectSet<order> _orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<team> teams
        {
            get
            {
                if ((_teams == null))
                {
                    _teams = base.CreateObjectSet<team>("teams");
                }
                return _teams;
            }
        }
        private ObjectSet<team> _teams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategories(category category)
        {
            base.AddObject("categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproducts(product product)
        {
            base.AddObject("products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the contact_us EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocontact_us(contact_us contact_us)
        {
            base.AddObject("contact_us", contact_us);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the menus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomenus(menu menu)
        {
            base.AddObject("menus", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the news EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonews(news news)
        {
            base.AddObject("news", news);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToorders(order order)
        {
            base.AddObject("orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the teams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToteams(team team)
        {
            base.AddObject("teams", team);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cakeshopModel", Name="category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new category object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static category Createcategory(global::System.Int32 id)
        {
            category category = new category();
            category.id = id;
            return category;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String meta
        {
            get
            {
                return _meta;
            }
            set
            {
                OnmetaChanging(value);
                ReportPropertyChanging("meta");
                _meta = StructuralObject.SetValidValue(value, true, "meta");
                ReportPropertyChanged("meta");
                OnmetaChanged();
            }
        }
        private global::System.String _meta;
        partial void OnmetaChanging(global::System.String value);
        partial void OnmetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hide
        {
            get
            {
                return _hide;
            }
            set
            {
                OnhideChanging(value);
                ReportPropertyChanging("hide");
                _hide = StructuralObject.SetValidValue(value, "hide");
                ReportPropertyChanged("hide");
                OnhideChanged();
            }
        }
        private Nullable<global::System.Boolean> _hide;
        partial void OnhideChanging(Nullable<global::System.Boolean> value);
        partial void OnhideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order
        {
            get
            {
                return _order;
            }
            set
            {
                OnorderChanging(value);
                ReportPropertyChanging("order");
                _order = StructuralObject.SetValidValue(value, "order");
                ReportPropertyChanged("order");
                OnorderChanged();
            }
        }
        private Nullable<global::System.Int32> _order;
        partial void OnorderChanging(Nullable<global::System.Int32> value);
        partial void OnorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datebegin
        {
            get
            {
                return _datebegin;
            }
            set
            {
                OndatebeginChanging(value);
                ReportPropertyChanging("datebegin");
                _datebegin = StructuralObject.SetValidValue(value, "datebegin");
                ReportPropertyChanged("datebegin");
                OndatebeginChanged();
            }
        }
        private Nullable<global::System.DateTime> _datebegin;
        partial void OndatebeginChanging(Nullable<global::System.DateTime> value);
        partial void OndatebeginChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cakeshopModel", Name="contact_us")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class contact_us : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new contact_us object.
        /// </summary>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        public static contact_us Createcontact_us(global::System.String address, global::System.String email, global::System.String phone)
        {
            contact_us contact_us = new contact_us();
            contact_us.address = address;
            contact_us.email = email;
            contact_us.phone = phone;
            return contact_us;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                if (_address != value)
                {
                    OnaddressChanging(value);
                    ReportPropertyChanging("address");
                    _address = StructuralObject.SetValidValue(value, false, "address");
                    ReportPropertyChanged("address");
                    OnaddressChanged();
                }
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                if (_email != value)
                {
                    OnemailChanging(value);
                    ReportPropertyChanging("email");
                    _email = StructuralObject.SetValidValue(value, false, "email");
                    ReportPropertyChanged("email");
                    OnemailChanged();
                }
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                if (_phone != value)
                {
                    OnphoneChanging(value);
                    ReportPropertyChanging("phone");
                    _phone = StructuralObject.SetValidValue(value, false, "phone");
                    ReportPropertyChanged("phone");
                    OnphoneChanged();
                }
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cakeshopModel", Name="menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new menu object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static menu Createmenu(global::System.Int32 id)
        {
            menu menu = new menu();
            menu.id = id;
            return menu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String meta
        {
            get
            {
                return _meta;
            }
            set
            {
                OnmetaChanging(value);
                ReportPropertyChanging("meta");
                _meta = StructuralObject.SetValidValue(value, true, "meta");
                ReportPropertyChanged("meta");
                OnmetaChanged();
            }
        }
        private global::System.String _meta;
        partial void OnmetaChanging(global::System.String value);
        partial void OnmetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hide
        {
            get
            {
                return _hide;
            }
            set
            {
                OnhideChanging(value);
                ReportPropertyChanging("hide");
                _hide = StructuralObject.SetValidValue(value, "hide");
                ReportPropertyChanged("hide");
                OnhideChanged();
            }
        }
        private Nullable<global::System.Boolean> _hide;
        partial void OnhideChanging(Nullable<global::System.Boolean> value);
        partial void OnhideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order
        {
            get
            {
                return _order;
            }
            set
            {
                OnorderChanging(value);
                ReportPropertyChanging("order");
                _order = StructuralObject.SetValidValue(value, "order");
                ReportPropertyChanged("order");
                OnorderChanged();
            }
        }
        private Nullable<global::System.Int32> _order;
        partial void OnorderChanging(Nullable<global::System.Int32> value);
        partial void OnorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datebegin
        {
            get
            {
                return _datebegin;
            }
            set
            {
                OndatebeginChanging(value);
                ReportPropertyChanging("datebegin");
                _datebegin = StructuralObject.SetValidValue(value, "datebegin");
                ReportPropertyChanged("datebegin");
                OndatebeginChanged();
            }
        }
        private Nullable<global::System.DateTime> _datebegin;
        partial void OndatebeginChanging(Nullable<global::System.DateTime> value);
        partial void OndatebeginChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cakeshopModel", Name="news")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class news : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new news object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static news Createnews(global::System.Int32 id)
        {
            news news = new news();
            news.id = id;
            return news;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String img
        {
            get
            {
                return _img;
            }
            set
            {
                OnimgChanging(value);
                ReportPropertyChanging("img");
                _img = StructuralObject.SetValidValue(value, true, "img");
                ReportPropertyChanged("img");
                OnimgChanged();
            }
        }
        private global::System.String _img;
        partial void OnimgChanging(global::System.String value);
        partial void OnimgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, true, "link");
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detail
        {
            get
            {
                return _detail;
            }
            set
            {
                OndetailChanging(value);
                ReportPropertyChanging("detail");
                _detail = StructuralObject.SetValidValue(value, true, "detail");
                ReportPropertyChanged("detail");
                OndetailChanged();
            }
        }
        private global::System.String _detail;
        partial void OndetailChanging(global::System.String value);
        partial void OndetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String meta
        {
            get
            {
                return _meta;
            }
            set
            {
                OnmetaChanging(value);
                ReportPropertyChanging("meta");
                _meta = StructuralObject.SetValidValue(value, true, "meta");
                ReportPropertyChanged("meta");
                OnmetaChanged();
            }
        }
        private global::System.String _meta;
        partial void OnmetaChanging(global::System.String value);
        partial void OnmetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hide
        {
            get
            {
                return _hide;
            }
            set
            {
                OnhideChanging(value);
                ReportPropertyChanging("hide");
                _hide = StructuralObject.SetValidValue(value, "hide");
                ReportPropertyChanged("hide");
                OnhideChanged();
            }
        }
        private Nullable<global::System.Boolean> _hide;
        partial void OnhideChanging(Nullable<global::System.Boolean> value);
        partial void OnhideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order
        {
            get
            {
                return _order;
            }
            set
            {
                OnorderChanging(value);
                ReportPropertyChanging("order");
                _order = StructuralObject.SetValidValue(value, "order");
                ReportPropertyChanged("order");
                OnorderChanged();
            }
        }
        private Nullable<global::System.Int32> _order;
        partial void OnorderChanging(Nullable<global::System.Int32> value);
        partial void OnorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datebegin
        {
            get
            {
                return _datebegin;
            }
            set
            {
                OndatebeginChanging(value);
                ReportPropertyChanging("datebegin");
                _datebegin = StructuralObject.SetValidValue(value, "datebegin");
                ReportPropertyChanged("datebegin");
                OndatebeginChanged();
            }
        }
        private Nullable<global::System.DateTime> _datebegin;
        partial void OndatebeginChanging(Nullable<global::System.DateTime> value);
        partial void OndatebeginChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cakeshopModel", Name="order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new order object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static order Createorder(global::System.Int32 id)
        {
            order order = new order();
            order.id = id;
            return order;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> oderDate
        {
            get
            {
                return _oderDate;
            }
            set
            {
                OnoderDateChanging(value);
                ReportPropertyChanging("oderDate");
                _oderDate = StructuralObject.SetValidValue(value, "oderDate");
                ReportPropertyChanged("oderDate");
                OnoderDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _oderDate;
        partial void OnoderDateChanging(Nullable<global::System.DateTime> value);
        partial void OnoderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String customerName
        {
            get
            {
                return _customerName;
            }
            set
            {
                OncustomerNameChanging(value);
                ReportPropertyChanging("customerName");
                _customerName = StructuralObject.SetValidValue(value, true, "customerName");
                ReportPropertyChanged("customerName");
                OncustomerNameChanged();
            }
        }
        private global::System.String _customerName;
        partial void OncustomerNameChanging(global::System.String value);
        partial void OncustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String productName
        {
            get
            {
                return _productName;
            }
            set
            {
                OnproductNameChanging(value);
                ReportPropertyChanging("productName");
                _productName = StructuralObject.SetValidValue(value, true, "productName");
                ReportPropertyChanged("productName");
                OnproductNameChanged();
            }
        }
        private global::System.String _productName;
        partial void OnproductNameChanging(global::System.String value);
        partial void OnproductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value, "quantity");
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private Nullable<global::System.Int32> _quantity;
        partial void OnquantityChanging(Nullable<global::System.Int32> value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, "price");
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Double> _price;
        partial void OnpriceChanging(Nullable<global::System.Double> value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> totalAmount
        {
            get
            {
                return _totalAmount;
            }
            set
            {
                OntotalAmountChanging(value);
                ReportPropertyChanging("totalAmount");
                _totalAmount = StructuralObject.SetValidValue(value, "totalAmount");
                ReportPropertyChanged("totalAmount");
                OntotalAmountChanged();
            }
        }
        private Nullable<global::System.Double> _totalAmount;
        partial void OntotalAmountChanging(Nullable<global::System.Double> value);
        partial void OntotalAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String payment
        {
            get
            {
                return _payment;
            }
            set
            {
                OnpaymentChanging(value);
                ReportPropertyChanging("payment");
                _payment = StructuralObject.SetValidValue(value, true, "payment");
                ReportPropertyChanged("payment");
                OnpaymentChanged();
            }
        }
        private global::System.String _payment;
        partial void OnpaymentChanging(global::System.String value);
        partial void OnpaymentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastUpdateDate
        {
            get
            {
                return _lastUpdateDate;
            }
            set
            {
                OnlastUpdateDateChanging(value);
                ReportPropertyChanging("lastUpdateDate");
                _lastUpdateDate = StructuralObject.SetValidValue(value, "lastUpdateDate");
                ReportPropertyChanged("lastUpdateDate");
                OnlastUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastUpdateDate;
        partial void OnlastUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnlastUpdateDateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cakeshopModel", Name="product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new product object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="categoryid">Initial value of the categoryid property.</param>
        public static product Createproduct(global::System.Int32 id, global::System.Int32 categoryid)
        {
            product product = new product();
            product.id = id;
            product.categoryid = categoryid;
            return product;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 categoryid
        {
            get
            {
                return _categoryid;
            }
            set
            {
                OncategoryidChanging(value);
                ReportPropertyChanging("categoryid");
                _categoryid = StructuralObject.SetValidValue(value, "categoryid");
                ReportPropertyChanged("categoryid");
                OncategoryidChanged();
            }
        }
        private global::System.Int32 _categoryid;
        partial void OncategoryidChanging(global::System.Int32 value);
        partial void OncategoryidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, "price");
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Double> _price;
        partial void OnpriceChanging(Nullable<global::System.Double> value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String img
        {
            get
            {
                return _img;
            }
            set
            {
                OnimgChanging(value);
                ReportPropertyChanging("img");
                _img = StructuralObject.SetValidValue(value, true, "img");
                ReportPropertyChanged("img");
                OnimgChanged();
            }
        }
        private global::System.String _img;
        partial void OnimgChanging(global::System.String value);
        partial void OnimgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value, true, "size");
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private global::System.String _size;
        partial void OnsizeChanging(global::System.String value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String meta
        {
            get
            {
                return _meta;
            }
            set
            {
                OnmetaChanging(value);
                ReportPropertyChanging("meta");
                _meta = StructuralObject.SetValidValue(value, true, "meta");
                ReportPropertyChanged("meta");
                OnmetaChanged();
            }
        }
        private global::System.String _meta;
        partial void OnmetaChanging(global::System.String value);
        partial void OnmetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hide
        {
            get
            {
                return _hide;
            }
            set
            {
                OnhideChanging(value);
                ReportPropertyChanging("hide");
                _hide = StructuralObject.SetValidValue(value, "hide");
                ReportPropertyChanged("hide");
                OnhideChanged();
            }
        }
        private Nullable<global::System.Boolean> _hide;
        partial void OnhideChanging(Nullable<global::System.Boolean> value);
        partial void OnhideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order
        {
            get
            {
                return _order;
            }
            set
            {
                OnorderChanging(value);
                ReportPropertyChanging("order");
                _order = StructuralObject.SetValidValue(value, "order");
                ReportPropertyChanged("order");
                OnorderChanged();
            }
        }
        private Nullable<global::System.Int32> _order;
        partial void OnorderChanging(Nullable<global::System.Int32> value);
        partial void OnorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datebegin
        {
            get
            {
                return _datebegin;
            }
            set
            {
                OndatebeginChanging(value);
                ReportPropertyChanging("datebegin");
                _datebegin = StructuralObject.SetValidValue(value, "datebegin");
                ReportPropertyChanged("datebegin");
                OndatebeginChanged();
            }
        }
        private Nullable<global::System.DateTime> _datebegin;
        partial void OndatebeginChanging(Nullable<global::System.DateTime> value);
        partial void OndatebeginChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cakeshopModel", Name="team")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class team : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new team object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static team Createteam(global::System.Int32 id)
        {
            team team = new team();
            team.id = id;
            return team;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String job_title
        {
            get
            {
                return _job_title;
            }
            set
            {
                Onjob_titleChanging(value);
                ReportPropertyChanging("job_title");
                _job_title = StructuralObject.SetValidValue(value, true, "job_title");
                ReportPropertyChanged("job_title");
                Onjob_titleChanged();
            }
        }
        private global::System.String _job_title;
        partial void Onjob_titleChanging(global::System.String value);
        partial void Onjob_titleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String img
        {
            get
            {
                return _img;
            }
            set
            {
                OnimgChanging(value);
                ReportPropertyChanging("img");
                _img = StructuralObject.SetValidValue(value, true, "img");
                ReportPropertyChanged("img");
                OnimgChanged();
            }
        }
        private global::System.String _img;
        partial void OnimgChanging(global::System.String value);
        partial void OnimgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String twitter
        {
            get
            {
                return _twitter;
            }
            set
            {
                OntwitterChanging(value);
                ReportPropertyChanging("twitter");
                _twitter = StructuralObject.SetValidValue(value, true, "twitter");
                ReportPropertyChanged("twitter");
                OntwitterChanged();
            }
        }
        private global::System.String _twitter;
        partial void OntwitterChanging(global::System.String value);
        partial void OntwitterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String facebook
        {
            get
            {
                return _facebook;
            }
            set
            {
                OnfacebookChanging(value);
                ReportPropertyChanging("facebook");
                _facebook = StructuralObject.SetValidValue(value, true, "facebook");
                ReportPropertyChanged("facebook");
                OnfacebookChanged();
            }
        }
        private global::System.String _facebook;
        partial void OnfacebookChanging(global::System.String value);
        partial void OnfacebookChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String instagram
        {
            get
            {
                return _instagram;
            }
            set
            {
                OninstagramChanging(value);
                ReportPropertyChanging("instagram");
                _instagram = StructuralObject.SetValidValue(value, true, "instagram");
                ReportPropertyChanged("instagram");
                OninstagramChanged();
            }
        }
        private global::System.String _instagram;
        partial void OninstagramChanging(global::System.String value);
        partial void OninstagramChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String linked_in
        {
            get
            {
                return _linked_in;
            }
            set
            {
                Onlinked_inChanging(value);
                ReportPropertyChanging("linked_in");
                _linked_in = StructuralObject.SetValidValue(value, true, "linked_in");
                ReportPropertyChanged("linked_in");
                Onlinked_inChanged();
            }
        }
        private global::System.String _linked_in;
        partial void Onlinked_inChanging(global::System.String value);
        partial void Onlinked_inChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true, "phone");
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_of_birth
        {
            get
            {
                return _date_of_birth;
            }
            set
            {
                Ondate_of_birthChanging(value);
                ReportPropertyChanging("date_of_birth");
                _date_of_birth = StructuralObject.SetValidValue(value, "date_of_birth");
                ReportPropertyChanged("date_of_birth");
                Ondate_of_birthChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_of_birth;
        partial void Ondate_of_birthChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_of_birthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hide
        {
            get
            {
                return _hide;
            }
            set
            {
                OnhideChanging(value);
                ReportPropertyChanging("hide");
                _hide = StructuralObject.SetValidValue(value, "hide");
                ReportPropertyChanged("hide");
                OnhideChanged();
            }
        }
        private Nullable<global::System.Boolean> _hide;
        partial void OnhideChanging(Nullable<global::System.Boolean> value);
        partial void OnhideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order
        {
            get
            {
                return _order;
            }
            set
            {
                OnorderChanging(value);
                ReportPropertyChanging("order");
                _order = StructuralObject.SetValidValue(value, "order");
                ReportPropertyChanged("order");
                OnorderChanged();
            }
        }
        private Nullable<global::System.Int32> _order;
        partial void OnorderChanging(Nullable<global::System.Int32> value);
        partial void OnorderChanged();

        #endregion

    }

    #endregion

}
