//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCakes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<System.DateTime> oderDate { get; set; }
        public string customerName { get; set; }
        public string productName { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public string payment { get; set; }
        public Nullable<System.DateTime> lastUpdateDate { get; set; }
    }
}
